spring:
  application:
    name: AuthorizationService
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: off
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: 9000



token:
  format: self-contained
  access-token-ttl: 300
  refresh-token-ttl: 2592000
  authorization-code-ttl: 300
  reuse-refresh-tokens: false
  id-token-signature-algorithm: RS256

authorization-server:
  issuer: http://localhost:9000




auth:
  allowed-scopes: openid, profile, email, phone, address, read, write
  allowed-grant-types: authorization_code, refresh_token, client_credentials
  client-authentication-methods: client_secret_basic, client_secret_post
client:
  require-proof-key: false
  require-authorization-consent: false


# ============================================
# EUREKA CLIENT CONFIGURATION
# ============================================

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/

    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    disable-delta: false
    healthcheck:
      enabled: true
    refresh:
      enable: true
    region: us-east-1
    availability-zones:
      us-east-1: zone1, zone2
    prefer-same-zone-eureka: true
    webclient:
      enabled: false
    timeout:
      connect-timeout: 5000
      connect-request-timeout: 8000
      socket-timeout: 10000
    tls:
      enabled: false

    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8
    eureka-server-total-connections: 200
    eureka-server-total-connections-per-host: 50
    eureka-connection-idle-timeout-seconds: 30
    filter-only-up-instances: true
    log-delta-diff: true
    g-zip-content: true

  instance:
    hostname: localhost
    prefer-ip-address: false
    non-secure-port: ${server.port}
    non-secure-port-enabled: true   # ← enable HTTP
    secure-port-enabled: false      # ← disable HTTPS
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
    metadata-map:
      zone: zone1
      version: 1.0.0
      profile: dev
    initial-status: UP


# auth-service application.yml
springdoc:
  api-docs:
    path: /v3/api-docs